spring:
  application:
    name: TechManage

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=SET TIME ZONE 'UTC'
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      platform: h2

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui