CREATE TABLE tb_user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name  VARCHAR(255)                            NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255)                            NOT NULL,
    birth_date TIMESTAMP                               NOT NULL,
    user_type  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_email UNIQUE (email);